# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190926_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_database',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yayin tarihi'),
        ),
    ]
